In [1]:
import pandas as pd

Import CSV

In [3]:
df=pd.read_csv("../data/DCA_Legally_Operating_Businesses_08092021.csv")

In [4]:
df

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
0,1070856-DCA,Business,12/31/04,Inactive,1/5/01,Tobacco Retail Dealer,"DOOKHAN, HAROLD",CAESAR'S GROCERY & DELI,8619,SUTTER AVE,...,410.0,32.0,4190296.0,4.091470e+09,QN56,54.0,NaN,-73.850393,40.675896,"(40.675896079942085, -73.8503934722929)"
1,1398066-DCA,Business,7/26/20,Inactive,6/27/11,Sidewalk Cafe,UNCLE ABIES DELI ON FIRST INC.,2ND AVENUE DELI,1442,1ST AVE,...,108.0,5.0,1045916.0,1.014690e+09,MN31,132.0,"Sidewalk Cafe Type: Enclosed, Square Feet: 565...",-73.954638,40.769655,"(40.769654765206866, -73.95463753329575)"
2,2096068-1-DCA,Business,11/30/21,Active,7/27/20,Electronic Cigarette Dealer,TWO BROTHERS DELI & GRILL CORP,NaN,10720,LIBERTY AVE,...,410.0,32.0,4202231.0,4.095300e+09,NaN,NaN,NaN,-73.834169,40.683485,"(40.683485109935305, -73.83416943297395)"
3,2041423-DCA,Business,3/31/22,Active,7/28/16,Stoop Line Stand,JOEY EXPRESS DELI INC,NaN,1951,SOUTHERN BLVD,...,206.0,17.0,2010159.0,2.029600e+09,NaN,NaN,"Product Category: Fruits, Vegetables, Soft Dri...",-73.885705,40.842540,"(40.84253987666255, -73.88570515700712)"
4,2078168-DCA,Business,3/31/22,Active,9/14/18,Stoop Line Stand,"BAILEY'S QUICK STOP DELI, INC",NaN,141,W 231ST ST,...,208.0,14.0,2016143.0,2.032670e+09,NaN,NaN,"Product Category: Fruits, Vegetables, Soft Dri...",-73.902582,40.878096,"(40.878096495652684, -73.90258191620947)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14771,1348137-DCA,Business,12/31/15,Inactive,3/24/10,Tobacco Retail Dealer,WILLIAM VERAS BODEGA CORPORATION,NaN,257,DYCKMAN ST,...,112.0,7.0,1065057.0,1.022470e+09,MN01,295.0,NaN,-73.928439,40.866522,"(40.86652183698957, -73.9284387403715)"
14772,2035641-1-DCA,Business,12/31/17,Inactive,4/7/16,Tobacco Retail Dealer,BODEGAS UNLIMITED LLC,NaN,101,SHERMAN AVE,...,112.0,10.0,1064745.0,1.022200e+09,MN01,291.0,NaN,-73.925231,40.863852,"(40.863851956918054, -73.92523119238143)"
14773,2009141-DCA,Business,3/31/18,Inactive,6/4/14,Stoop Line Stand,48 BODEGA INC,NaN,4720,BROADWAY,...,401.0,26.0,4013131.0,4.007230e+09,QN70,161.0,"Product Category: Fruits, Vegetables, Soft Dri...",-73.913184,40.756228,"(40.75622840356721, -73.91318438034456)"
14774,2032310-2-DCA,Business,12/31/22,Active,1/11/16,Tobacco Retail Dealer,BODEGA BUILT INC,NaN,601,E 180TH ST,...,206.0,15.0,2012024.0,2.030700e+09,BX17,373.0,NaN,-73.891375,40.849393,"(40.8493934027397, -73.89137546076559)"
14775,1459434-DCA,Business,12/31/22,Active,3/8/13,Tobacco Retail Dealer,48 BODEGA INC,NaN,4720,BROADWAY,...,401.0,26.0,4013131.0,4.007230e+09,QN70,161.0,NaN,-73.913184,40.756228,"(40.75622840356721, -73.91318438034456)"

Change License Expiration Date to Date Time

In [6]:
df["License Expiration Date"].apply(pd.to_datetime)

0       2004-12-31
1       2020-07-26
2       2021-11-30
3       2022-03-31
4       2022-03-31
           ...
14771   2015-12-31
14772   2017-12-31
14773   2018-03-31
14774   2022-12-31
14775   2022-12-31
Name: License Expiration Date, Length: 14776, dtype: datetime64[ns]

In [7]:
df["License Expiration Date"] = df["License Expiration Date"].apply(pd.to_datetime)

In [8]:
df.sort_values(by= "License Expiration Date")

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
5843,0982124-DCA,Business,2000-03-31,Inactive,4/7/98,Stoop Line Stand,"D & K DELI GROCERY, INC.",NaN,8265,PARSONS BLVD,...,408.0,24.0,4148528.0,4.068590e+09,QN38,1267.0,"Product Category: Fruits, Vegetables, Soft Dri...",-73.808049,40.716684,"(40.716683700984525, -73.80804889232282)"
5607,1009232-DCA,Business,2000-03-31,Inactive,5/12/99,Stoop Line Stand,ALANIS DELI GROCERY CORP.,NaN,2565,GRAND CONCOURSE,...,207.0,15.0,2013820.0,2.031670e+09,BX05,401.0,"Product Category: Fruits, Vegetables, Soft Dri...",-73.896135,40.863786,"(40.86378551881625, -73.89613504324691)"
5507,1045015-DCA,Business,2000-12-31,Inactive,8/11/98,Tobacco Retail Dealer,GREEN VILLAGE DELI INC.,CLASSIC SMOKE SHOP,206,THOMPSON ST,...,102.0,1.0,1077847.0,1.005370e+09,MN23,65.0,NaN,-73.999351,40.728794,"(40.72879439653422, -73.99935055813754)"
2996,1044719-DCA,Business,2000-12-31,Inactive,12/31/00,Tobacco Retail Dealer,AKHTAR HUSSAIN,NEW ALAMO DELI & GROCERY,607,HENRY ST,...,306.0,39.0,3005130.0,3.003600e+09,BK33,65.0,NaN,-74.001060,40.680679,"(40.68067867055645, -74.00105998969049)"
5304,1161169-DCA,Business,2000-12-31,Inactive,3/2/04,Tobacco Retail Dealer,"BASIC DELI GROCEERY GROUP, CORP",NaN,1292,WASHINGTON AVE,...,203.0,16.0,2001333.0,2.023730e+09,BX01,145.0,NaN,-73.905933,40.833004,"(40.83300380563153, -73.90593276132783)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14600,2003077-787-DCA,Business,2023-12-31,Active,1/30/14,Tobacco Retail Dealer,LOW PRICE DELI AND GROCERY INC.,NaN,682,CARY AVE,...,501.0,49.0,5006047.0,5.002230e+09,SI22,125.0,NaN,-74.124349,40.631776,"(40.631776292578444, -74.12434948177653)"
14589,2035256-1-DCA,Business,2023-12-31,Active,3/30/16,Tobacco Retail Dealer,CASTLETON DELI & GROCERY CORP,NaN,1078,CASTLETON AVE,...,501.0,49.0,5005562.0,5.002080e+09,SI22,13302.0,NaN,-74.118694,40.634420,"(40.63442001336451, -74.11869423423543)"
14656,2080595-1-DCA,Business,2023-12-31,Active,12/11/18,Tobacco Retail Dealer,HEALTHY GREENS GOURMET DELI CORP,NaN,48,3RD AVE,...,103.0,2.0,1008975.0,1.005560e+09,MN22,42.0,NaN,-73.988995,40.730817,"(40.73081675728912, -73.98899523443829)"
401,2000137-49-DCA,Business,NaT,Inactive,10/24/13,Tobacco Retail Dealer,MARILYN'S DELI GROCERY CORP,NaN,1027,WALTON AVE,...,204.0,17.0,2002939.0,2.024770e+09,BX63,195.0,NaN,-73.922027,40.830735,"(40.83073495266584, -73.92202706239397)"
2133,2091865-2-DCA,Business,NaT,Inactive,10/30/19,Tobacco Retail Dealer,DAD'S DELI INC,NaN,70,LORRAINE ST,...,306.0,38.0,3008668.0,3.005800e+09,NaN,NaN,NaN,-74.007055,40.674431,"(40.67443135345515, -74.00705512079273)"

Make the Date Time change permanent.

In [11]:
df = df.sort_values(by= "License Expiration Date", ascending=False)

Remove Duplicates within Business Name

In [12]:
df.drop_duplicates(subset=["Business Name"])

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
14560,2035552-1-DCA,Business,2023-12-31,Active,4/5/16,Tobacco Retail Dealer,64 FULTON ST. FOOD CORP.,SEAPORT DELI,64,FULTON ST,...,101.0,1.0,1001176.0,1.000760e+09,MN25,1502.0,NaN,-74.005136,40.708769,"(40.708768518071146, -74.00513626321822)"
14656,2080595-1-DCA,Business,2023-12-31,Active,12/11/18,Tobacco Retail Dealer,HEALTHY GREENS GOURMET DELI CORP,NaN,48,3RD AVE,...,103.0,2.0,1008975.0,1.005560e+09,MN22,42.0,NaN,-73.988995,40.730817,"(40.73081675728912, -73.98899523443829)"
14563,2066162-1-DCA,Business,2023-12-31,Active,2/15/18,Tobacco Retail Dealer,CROWN STAR DELI INC.,NaN,240,UTICA AVE,...,308.0,35.0,3037074.0,3.013840e+09,BK61,351.0,NaN,-73.930982,40.670395,"(40.6703952600378, -73.93098151122031)"
14640,2097659-1-DCA,Business,2023-12-31,Active,2/2/21,Tobacco Retail Dealer,THE ELLINGTON DELI DELI CORP,NaN,934,COLUMBUS AVE,...,107.0,7.0,1055942.0,1.018600e+09,NaN,NaN,NaN,-73.962993,40.799079,"(40.799078554267176, -73.96299329351787)"
14589,2035256-1-DCA,Business,2023-12-31,Active,3/30/16,Tobacco Retail Dealer,CASTLETON DELI & GROCERY CORP,NaN,1078,CASTLETON AVE,...,501.0,49.0,5005562.0,5.002080e+09,SI22,13302.0,NaN,-74.118694,40.634420,"(40.63442001336451, -74.11869423423543)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,1044719-DCA,Business,2000-12-31,Inactive,12/31/00,Tobacco Retail Dealer,AKHTAR HUSSAIN,NEW ALAMO DELI & GROCERY,607,HENRY ST,...,306.0,39.0,3005130.0,3.003600e+09,BK33,65.0,NaN,-74.001060,40.680679,"(40.68067867055645, -74.00105998969049)"
4103,1045822-DCA,Business,2000-12-31,Inactive,8/31/98,Tobacco Retail Dealer,AHMED HAZIM MOZEB,STOP 1 DELI,16824,HILLSIDE AVE,...,412.0,27.0,0.0,4.000000e+09,QN61,460.0,NaN,-73.794097,40.710259,"(40.710258792660525, -73.79409741960198)"
5843,0982124-DCA,Business,2000-03-31,Inactive,4/7/98,Stoop Line Stand,"D & K DELI GROCERY, INC.",NaN,8265,PARSONS BLVD,...,408.0,24.0,4148528.0,4.068590e+09,QN38,1267.0,"Product Category: Fruits, Vegetables, Soft Dri...",-73.808049,40.716684,"(40.716683700984525, -73.80804889232282)"
401,2000137-49-DCA,Business,NaT,Inactive,10/24/13,Tobacco Retail Dealer,MARILYN'S DELI GROCERY CORP,NaN,1027,WALTON AVE,...,204.0,17.0,2002939.0,2.024770e+09,BX63,195.0,NaN,-73.922027,40.830735,"(40.83073495266584, -73.92202706239397)"
2133,2091865-2-DCA,Business,NaT,Inactive,10/30/19,Tobacco Retail Dealer,DAD'S DELI INC,NaN,70,LORRAINE ST,...,306.0,38.0,3008668.0,3.005800e+09,NaN,NaN,NaN,-74.007055,40.674431,"(40.67443135345515, -74.00705512079273)"

In [13]:
df=df.drop_duplicates(subset=["Business Name"])

In [14]:
df.columns

Index(['DCA License Number', 'License Type', 'License Expiration Date',
       'License Status', 'License Creation Date', 'Industry', 'Business Name',
       'Business Name 2', 'Address Building', 'Address Street Name',
       'Secondary Address Street Name', 'Address City', 'Address State',
       'Address ZIP', 'Contact Phone Number', 'Address Borough',
       'Borough Code', 'Community Board', 'Council District', 'BIN', 'BBL',
       'NTA', 'Census Tract', 'Detail', 'Longitude', 'Latitude', 'Location'],
      dtype='object')

Remove dates from before 2018

In [50]:
df_filtered=df.loc[(df["License Expiration Date"]) >= "2018-01-01"]

Find the highest counts of Inactive licenses by zip code

In [53]:
df_filtered[["License Status", "Address ZIP", "Address Borough"]]

      License Status  Address ZIP Address Borough
14560         Active        10038       Manhattan
14656         Active        10003       Manhattan
14563         Active        11213        Brooklyn
14640         Active        10025       Manhattan
14589         Active        10310   Staten Island
...              ...          ...             ...
6829        Inactive        10454           Bronx
12500       Inactive        11232        Brooklyn
9048        Inactive        10461           Bronx
10259       Inactive        11378          Queens
8431        Inactive        10453           Bronx

[4018 rows x 3 columns]

In [54]:
df_filtered[["License Status", "Address ZIP", "Address Borough", "Business Name"]].groupby(["Address Borough", "Address ZIP", "License Status"]).count()

                                            Business Name
Address Borough Address ZIP License Status
Bronx           10451       Active                     20
                            Inactive                   27
                10452       Active                     35
                            Inactive                   29
                10453       Active                     26
...                                                   ...
Staten Island   10310       Inactive                    9
                10312       Active                      4
                            Inactive                    3
                10314       Active                      5
                            Inactive                    7

[325 rows x 1 columns]

In [55]:
active_inactive_count = df_filtered[["License Status", "Address ZIP", "Address Borough", "Business Name"]].groupby(["Address Borough", "Address ZIP", "License Status"]).count().reset_index()

In [56]:
active_inactive_count

    Address Borough  Address ZIP License Status  Business Name
0             Bronx        10451         Active             20
1             Bronx        10451       Inactive             27
2             Bronx        10452         Active             35
3             Bronx        10452       Inactive             29
4             Bronx        10453         Active             26
..              ...          ...            ...            ...
320   Staten Island        10310       Inactive              9
321   Staten Island        10312         Active              4
322   Staten Island        10312       Inactive              3
323   Staten Island        10314         Active              5
324   Staten Island        10314       Inactive              7

[325 rows x 4 columns]

In [57]:
active_inactive_count

    Address Borough  Address ZIP License Status  Business Name
0             Bronx        10451         Active             20
1             Bronx        10451       Inactive             27
2             Bronx        10452         Active             35
3             Bronx        10452       Inactive             29
4             Bronx        10453         Active             26
..              ...          ...            ...            ...
320   Staten Island        10310       Inactive              9
321   Staten Island        10312         Active              4
322   Staten Island        10312       Inactive              3
323   Staten Island        10314         Active              5
324   Staten Island        10314       Inactive              7

[325 rows x 4 columns]

In [58]:
active_inactive_count[active_inactive_count["License Status"].eq("Inactive")].sort_values(by="Business Name", ascending=False).head(10)

    Address Borough  Address ZIP License Status  Business Name
59         Brooklyn        11207       Inactive             55
250          Queens        11385       Inactive             38
11            Bronx        10456       Inactive             38
15            Bronx        10458       Inactive             33
109        Brooklyn        11233       Inactive             33
69         Brooklyn        11212       Inactive             32
61         Brooklyn        11208       Inactive             32
97         Brooklyn        11226       Inactive             31
5             Bronx        10453       Inactive             30
77         Brooklyn        11216       Inactive             30

Determine turnover— Find addresses with unique business owners

In [61]:
df_filtered.groupby(["Address Building", "Address Street Name", "Address ZIP"]).count().sort_values(by = "DCA License Number", ascending = False)

,,,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Secondary Address Street Name,Address City,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
Address Building,Address Street Name,Address ZIP,,,,,,,,,,,,,,,,,,,,,
71,LEXINGTON AVE,10010,4,4,4,4,4,4,4,1,0,4,...,4,4,4,4,3,3,0,4,4,4
16,E 183RD ST,10453,4,4,4,4,4,4,4,0,0,4,...,4,4,4,4,2,2,0,4,4,4
496,NOSTRAND AVE,11216,4,4,4,4,4,4,4,0,0,4,...,4,4,4,4,2,2,0,4,4,4
1919,CROPSEY AVE,11214,4,4,4,4,4,4,4,2,0,4,...,4,4,4,4,2,2,0,4,4,4
74,NAGLE AVE,10040,4,4,4,4,4,4,4,0,0,4,...,4,4,4,4,2,2,2,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22026,MERRICK BLVD,11413,1,1,1,1,1,1,1,0,0,1,...,1,1,1,1,1,1,0,1,1,1
2206A,FLATBUSH AVE,11234,1,1,1,1,1,1,1,0,0,1,...,1,1,1,1,1,1,0,1,1,1
2208,FULTON ST,11233,1,1,1,1,1,1,1,0,0,1,...,1,1,1,1,0,0,0,1,1,1
221,CENTRAL AVE,11221,1,1,1,1,1,1,1,0,0,1,...,1,1,1,1,1,1,0,1,1,1
994,MORRIS PARK AVE,10462,1,1,1,1,1,1,1,0,0,1,...,1,1,1,1,1,1,0,1,1,1

Zip Code 11216 has both one of the highest counts of inactive licenses in our date range, and an address with 4 different business owners. 

We will focus on that zip code to begin with. 

Bring up a new data frame showing just 11216.

In [67]:
df_filtered.columns

Index(['DCA License Number', 'License Type', 'License Expiration Date',
       'License Status', 'License Creation Date', 'Industry', 'Business Name',
       'Business Name 2', 'Address Building', 'Address Street Name',
       'Secondary Address Street Name', 'Address City', 'Address State',
       'Address ZIP', 'Contact Phone Number', 'Address Borough',
       'Borough Code', 'Community Board', 'Council District', 'BIN', 'BBL',
       'NTA', 'Census Tract', 'Detail', 'Longitude', 'Latitude', 'Location'],
      dtype='object')

In [87]:
df_filtered[df_filtered["Address ZIP"].eq(11216)]

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
14152,1394098-DCA,Business,2022-12-31,Active,6/1/11,Tobacco Retail Dealer,HALSEY SUPERMARKET DELI CORP.,NaN,169,HALSEY ST,...,303.0,36.0,3052690.0,3.018380e+09,BK75,249.0,NaN,-73.947075,40.682132,"(40.68213221261493, -73.94707507223367)"
14049,1043782-DCA,Business,2022-12-31,Active,11/30/00,Tobacco Retail Dealer,"SALEH, FAISUL T",NOSTRAND DELI & GROCERY,669,NOSTRAND AVE,...,308.0,36.0,3030990.0,3.012270e+09,BK61,31701.0,NaN,-73.950059,40.674443,"(40.674442689003634, -73.95005896262542)"
14106,2060628-2-DCA,Business,2022-12-31,Active,11/13/17,Tobacco Retail Dealer,THUNDER DELI CORP,NaN,725,NOSTRAND AVE,...,308.0,35.0,3031915.0,3.012480e+09,BK61,31702.0,NaN,-73.950252,40.672395,"(40.67239516966863, -73.95025155866516)"
14393,1473360-DCA,Business,2022-12-31,Active,9/12/13,Tobacco Retail Dealer,ONE STOP TO SHOP GOURMET & DELI CORP,NaN,1339,FULTON ST,...,303.0,36.0,3053248.0,3.018490e+09,BK75,249.0,NaN,-73.948003,40.680313,"(40.680312851038515, -73.94800310083563)"
14502,2049010-2-DCA,Business,2022-12-31,Active,3/2/17,Tobacco Retail Dealer,NEW WAY NATURAL MARKET AND DELI CORP,NaN,390,TOMPKINS AVE,...,303.0,36.0,3338716.0,3.018340e+09,BK75,267.0,NaN,-73.944038,40.683912,"(40.68391213302259, -73.94403775899217)"
14511,2059587-2-DCA,Business,2022-12-31,Inactive,10/19/17,Tobacco Retail Dealer,GATE FINEST DELI CORP,NaN,318,TOMPKINS AVE,...,303.0,36.0,3051170.0,3.018140e+09,BK75,265.0,NaN,-73.944612,40.686794,"(40.68679442152985, -73.94461225818598)"
11678,2099856-2-DCA,Business,2022-12-31,Active,7/2/21,Tobacco Retail Dealer,FULTON DELI AND SMOKE SHOP CORP,NaN,1403,FULTON ST,...,303.0,36.0,3053471.0,3.018540e+09,NaN,NaN,NaN,-73.945068,40.680155,"(40.68015503534684, -73.9450684449953)"
3351,1221510-DCA,Business,2022-12-31,Inactive,3/21/06,Tobacco Retail Dealer,DEAN DELI GROCERY CORP.,NaN,1050,DEAN ST,...,308.0,35.0,3030246.0,3.012110e+09,BK61,221.0,NaN,-73.955057,40.677486,"(40.67748596060282, -73.95505714467012)"
10353,2099566-2-DCA,Business,2022-12-31,Active,6/21/21,Tobacco Retail Dealer,JAYRAN DELI GROCERY INC,NaN,1050,DEAN ST,...,308.0,35.0,3030246.0,3.012110e+09,NaN,NaN,NaN,-73.955057,40.677486,"(40.67748596060282, -73.95505714467012)"
7804,2098906-2-DCA,Business,2022-12-31,Active,5/25/21,Tobacco Retail Dealer,613 FRESH DELI AND GROCERY CORP,NaN,613,NOSTRAND AVE,...,308.0,36.0,3337844.0,3.012130e+09,NaN,NaN,NaN,-73.949892,40.676213,"(40.67621299633303, -73.94989179930965)"
13881,2083558-2-DCA,Business,2022-12-31,Active,3/22/19,Tobacco Retail Dealer,TONY DELI GROCERY 1 CORP.,NaN,1478,BEDFORD AVE,...,308.0,35.0,3031803.0,3.012450e+09,BK61,219.0,NaN,-73.954375,40.672625,"(40.6726246953942, -73.9543754757304)"
13846,2059582-2-DCA,Business,2022-12-31,Active,10/19/17,Tobacco Retail Dealer,GREENLAND MINI MARKET DELI INC,NaN,784,MARCY AVE,...,303.0,36.0,3322225.0,3.018080e+09,BK75,251.0,NaN,-73.947536,40.686922,"(40.68692205131839, -73.94753641166716)"
13861,2090468-2-DCA,Business,2022-12-31,Active,9/12/19,Tobacco Retail Dealer,367 FAMOUS DELI CORP,NaN,753,MARCY AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947759,40.688152,"(40.68815181005619, -73.94775900442599)"
13816,1257496-DCA,Business,2022-12-31,Active,6/1/07,Tobacco Retail Dealer,"ALREZAKI, AHMED A & ALZOOKARI, MUGALLI S",CROWN HEIGHTS DELI & GROCERY,117,ROGERS AVE,...,308.0,36.0,3031491.0,3.012400e+09,BK61,31701.0,NaN,-73.952937,40.673437,"(40.67343656942923, -73.95293651891095)"
2582,2011041-1-DCA,Business,2021-12-31,Active,7/22/14,Tobacco Retail Dealer,PAPA DELI & GROCERY CORP.,NaN,849,MARCY AVE,...,303.0,36.0,3322392.0,3.018290e+09,BK75,267.0,NaN,-73.946983,40.684270,"(40.6842703482155, -73.94698323520508)"
2741,2046032-1-DCA,Business,2021-12-31,Active,11/30/16,Tobacco Retail Dealer,NOSTRAND FINEST DELI INC,NaN,792,NOSTRAND AVE,...,308.0,35.0,3032243.0,3.012540e+09,BK61,31702.0,NaN,-73.950357,40.671506,"(40.67150590758534, -73.95035676440332)"
3732,2082032-1-DCA,Business,2021-12-31,Active,2/6/19,Tobacco Retail Dealer,S GOURMET DELI CORP,NaN,1558,FULTON ST,...,303.0,36.0,3338777.0,3.018640e+09,BK61,271.0,NaN,-73.938720,40.679795,"(40.67979500866878, -73.93871970236303)"
13228,2095489-1-DCA,Business,2021-12-31,Inactive,3/23/20,Tobacco Retail Dealer,"GREEN PARK GOURMET DELI, INC",NaN,264,TOMPKINS AVE,...,303.0,36.0,3050449.0,3.017990e+09,NaN,NaN,NaN,-73.945047,40.688993,"(40.68899319146262, -73.94504674049102)"
173,2076764-1-DCA,Business,2021-12-31,Active,8/7/18,Tobacco Retail Dealer,JHOAN & BROTHER DELI GROCERY CORP,NaN,759,DEKALB AVE,...,303.0,36.0,3049501.0,3.017750e+09,BK75,261.0,NaN,-73.946223,40.691977,"(40.691977312521956, -73.94622344915649)"
7383,2080593-1-DCA,Business,2021-12-31,Inactive,12/10/18,Tobacco Retail Dealer,PRINCESS DELI AND SMOKE SHOP CORP,NaN,1318,FULTON ST,...,303.0,36.0,3053757.0,3.018610e+09,BK61,247.0,NaN,-73.948180,40.680307,"(40.68030744119197, -73.94817976904972)"
14326,2066589-1-DCA,Business,2021-12-31,Inactive,2/23/18,Tobacco Retail Dealer,BRKLYN DELI AND GRILL CORP,BROOKLYN GOURMET MARKET,1181,BEDFORD AVE,...,303.0,36.0,3329696.0,3.018270e+09,BK75,245.0,NaN,-73.953835,40.683024,"(40.6830244295472, -73.95383474133375)"
2230,1359661-DCA,Business,2021-12-31,Active,6/21/10,Tobacco Retail Dealer,SUPER EXPRESS DELI & GROCERY CORP. I,NaN,1205,BEDFORD AVE,...,303.0,36.0,3322555.0,3.018320e+09,BK75,245.0,NaN,-73.953673,40.682228,"(40.68222838047677, -73.9536730453112)"
11124,2043166-1-DCA,Business,2021-12-31,Inactive,9/1/16,Tobacco Retail Dealer,1403 FULTON GOURMET DELI CORP,NaN,1403,FULTON ST,...,303.0,36.0,3053471.0,3.018540e+09,BK75,269.0,NaN,-73.945068,40.680155,"(40.68015503534684, -73.9450684449953)"
14215,2097367-1-DCA,Business,2021-12-31,Active,12/30/20,Tobacco Retail Dealer,ALSQER DELI & GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,NaN,NaN,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
2721,2068454-1-DCA,Business,2021-11-30,Active,3/28/18,Electronic Cigarette Dealer,MY BUS STOP DELI AND GROCERY CORP,NaN,546A,NOSTRAND AVE,...,303.0,36.0,3053724.0,3.018600e+09,BK61,247.0,NaN,-73.949583,40.679984,"(40.67998418109907, -73.94958250923996)"
8348,2051985-2-DCA,Business,2020-12-31,Inactive,4/26/17,Tobacco Retail Dealer,BEDFORD DELI AND GROCERY CORP,NaN,1478,BEDFORD AVE,...,308.0,35.0,3031803.0,3.012450e+09,BK61,219.0,NaN,-73.954375,40.672625,"(40.6726246953942, -73.9543754757304)"
710,1211022-DCA,Business,2020-12-31,Inactive,9/26/05,Tobacco Retail Dealer,"KAID, AHMED M",TOMPKINS DELI GROCERY,264,TOMPKINS AVE,...,303.0,36.0,3050449.0,3.017990e+09,BK75,263.0,NaN,-73.945047,40.688993,"(40.68899319146262, -73.94504674049102)"
6333,1306164-DCA,Business,2020-12-31,Inactive,12/16/08,Tobacco Retail Dealer,G LINE DELI GROCERY INC,NaN,292,NOSTRAND AVE,...,303.0,36.0,3049897.0,3.017880e+09,BK75,243.0,NaN,-73.951465,40.689817,"(40.68981676356796, -73.95146456703722)"
540,2093313-2-DCA,Business,2020-12-31,Inactive,1/2/20,Tobacco Retail Dealer,NA ROCK DELI CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,NaN,NaN,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
1825,2053539-2-DCA,Business,2020-12-31,Inactive,5/25/17,Tobacco Retail Dealer,B DELI GROCERY CORP,NaN,684,NOSTRAND AVE,...,308.0,36.0,3030970.0,3.012260e+09,BK61,31701.0,NaN,-73.950026,40.675025,"(40.67502456711211, -73.9500260809846)"
240,2052492-2-DCA,Business,2020-12-31,Inactive,5/4/17,Tobacco Retail Dealer,KRISTAL DELI GROCERY NY CORP,NaN,1565,FULTON ST,...,303.0,36.0,3053680.0,3.018580e+09,BK35,273.0,NaN,-73.938835,40.679817,"(40.679817028236805, -73.93883505369406)"
2817,2066793-1-DCA,Business,2019-12-31,Inactive,2/23/18,Tobacco Retail Dealer,BARCELONA DELI AND GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,BK75,245.0,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
8005,2066670-1-DCA,Business,2019-12-31,Inactive,2/23/18,Tobacco Retail Dealer,MERIT DELI AND SMOKE SHOP CORP,NaN,1318,FULTON ST,...,303.0,36.0,3053757.0,3.018610e+09,BK61,247.0,NaN,-73.948180,40.680307,"(40.68030744119197, -73.94817976904972)"
10296,2039601-1-DCA,Business,2019-12-31,Inactive,6/28/16,Tobacco Retail Dealer,FAMILY FOOD & DELI CORP,NaN,1053,BEDFORD AVE,...,303.0,36.0,3050325.0,3.017970e+09,BK75,243.0,NaN,-73.954787,40.687812,"(40.68781168955238, -73.95478696214188)"
8830,2011197-1-DCA,Business,2019-12-31,Inactive,7/25/14,Tobacco Retail Dealer,J M DELI GROCERY CORP I,NaN,1369,FULTON ST,...,303.0,36.0,3053280.0,3.018500e+09,BK75,249.0,NaN,-73.946456,40.680233,"(40.68023254327992, -73.94645645386848)"
309,2066345-1-DCA,Business,2019-12-31,Inactive,2/20/18,Tobacco Retail Dealer,DEAN DELI CORPORATION,NaN,628,NOSTRAND AVE,...,308.0,36.0,3030004.0,3.012060e+09,BK61,315.0,NaN,-73.949844,40.676990,"(40.676989746923105, -73.94984434799078)"
12276,2066039-1-DCA,Business,2019-12-31,Inactive,2/13/18,Tobacco Retail Dealer,753 FAMOUS DELI CORP,NaN,753,MARCY AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947759,40.688152,"(40.68815181005619, -73.94775900442599)"
12092,1453015-DCA,Business,2019-12-31,Inactive,12/31/12,Tobacco Retail Dealer,RAJIH DELI AND GROCERY INC,NaN,689A,NOSTRAND AVE,...,308.0,36.0,3341625.0,3.012340e+09,BK61,31701.0,NaN,-73.950124,40.673713,"(40.6737126070741, -73.95012439987542)"
340,2006228-1383-DCA,Business,2019-12-31,Inactive,4/14/14,Tobacco Retail Dealer,367 deli and grocery inc,NaN,367,LEXINGTON AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947485,40.688080,"(40.68808032130511, -73.94748501902926)"
9378,2053835-2-DCA,Business,2018-12-31,Inactive,6/2/17,Tobacco Retail Dealer,K GOURMET DELI CORP,NaN,1558,FULTON ST,...,303.0,36.0,3338777.0,3.018640e+09,BK61,271.0,NaN,-73.938720,40.679795,"(40.67979500866878, -73.93871970236303)"
6968,2028147-2-DCA,Business,2018-12-31,Inactive,9/8/15,Tobacco Retail Dealer,J.V. DELI & GROCERY CORP.,NaN,925A,MARCY AVE,...,303.0,36.0,3331201.0,3.018510e+09,BK75,269.0,NaN,-73.946416,40.681391,"(40.681390818778496, -73.94641586396304)"
11482,1400210-DCA,Business,2018-12-31,Inactive,7/15/11,Tobacco Retail Dealer,NBA DELI AND GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,BK75,245.0,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
12618,2058481-2-DCA,Business,2018-12-31,Inactive,9/20/17,Tobacco Retail Dealer,SAKAFE DELI GROCERY CORP,NaN,813,MARCY AVE,...,303.0,36.0,3051455.0,3.018190e+09,BK75,265.0,NaN,-73.947278,40.685736,"(40.685736191780094, -73.94727773562067)"
7741,2049021-2-DCA,Business,2018-12-31,Inactive,3/2/17,Tobacco Retail Dealer,GOURMET 438 DELI INC,NaN,438,NOSTRAND AVE,...,303.0,36.0,3338697.0,3.018220e+09,BK75,245.0,NaN,-73.950333,40.684113,"(40.684112646005126, -73.95033295685029)"
10234,2059337-2-DCA,Business,2018-12-31,Inactive,10/13/17,Tobacco Retail Dealer,KARTER'S GROCERY & DELI INC,NaN,350,TOMPKINS AVE,...,303.0,36.0,3051462.0,3.018190e+09,BK75,265.0,NaN,-73.944375,40.685620,"(40.68561954494297, -73.94437525951625)"
7640,2052741-2-DCA,Business,2018-12-31,Inactive,5/10/17,Tobacco Retail Dealer,FANTASTIC DELI GROCERY CORP,NaN,925A,MARCY AVE,...,303.0,36.0,3331201.0,3.018510e+09,BK75,269.0,NaN,-73.946416,40.681391,"(40.681390818778496, -73.94641586396304)"
9204,1248248-DCA,Business,2018-12-31,Inactive,2/13/07,Tobacco Retail Dealer,SEVEN & ONE DELI GROCERY FULTON STREET CORP,NaN,1521,FULTON ST,...,303.0,36.0,3053619.0,3.018570e+09,BK75,269.0,NaN,-73.940457,40.679906,"(40.679905711966825, -73.9404573871347)"
12979,2048789-2-DCA,Business,2018-12-31,Inactive,2/28/17,Tobacco Retail Dealer,GATES GOURMET DELI AND SUPER MARKET CORP,NaN,349,NOSTRAND AVE,...,303.0,36.0,3000000.0,3.018088e+09,BK75,251.0,NaN,-73.950746,40.686311,"(40.686311385808224, -73.95074597604938)"
13309,2051395-2-DCA,Business,2018-12-31,Inactive,4/18/17,Tobacco Retail Dealer,SALMAN DELI CORP,NaN,1274,FULTON ST,...,303.0,36.0,3053721.0,3.018600e+09,BK61,247.0,NaN,-73.949899,40.680402,"(40.680401525131494, -73.94989946827623)"

In [88]:
df_11216 = df_filtered[df_filtered["Address ZIP"].eq(11216)]

In [89]:
df_11216

,DCA License Number,License Type,License Expiration Date,License Status,License Creation Date,Industry,Business Name,Business Name 2,Address Building,Address Street Name,...,Community Board,Council District,BIN,BBL,NTA,Census Tract,Detail,Longitude,Latitude,Location
14152,1394098-DCA,Business,2022-12-31,Active,6/1/11,Tobacco Retail Dealer,HALSEY SUPERMARKET DELI CORP.,NaN,169,HALSEY ST,...,303.0,36.0,3052690.0,3.018380e+09,BK75,249.0,NaN,-73.947075,40.682132,"(40.68213221261493, -73.94707507223367)"
14049,1043782-DCA,Business,2022-12-31,Active,11/30/00,Tobacco Retail Dealer,"SALEH, FAISUL T",NOSTRAND DELI & GROCERY,669,NOSTRAND AVE,...,308.0,36.0,3030990.0,3.012270e+09,BK61,31701.0,NaN,-73.950059,40.674443,"(40.674442689003634, -73.95005896262542)"
14106,2060628-2-DCA,Business,2022-12-31,Active,11/13/17,Tobacco Retail Dealer,THUNDER DELI CORP,NaN,725,NOSTRAND AVE,...,308.0,35.0,3031915.0,3.012480e+09,BK61,31702.0,NaN,-73.950252,40.672395,"(40.67239516966863, -73.95025155866516)"
14393,1473360-DCA,Business,2022-12-31,Active,9/12/13,Tobacco Retail Dealer,ONE STOP TO SHOP GOURMET & DELI CORP,NaN,1339,FULTON ST,...,303.0,36.0,3053248.0,3.018490e+09,BK75,249.0,NaN,-73.948003,40.680313,"(40.680312851038515, -73.94800310083563)"
14502,2049010-2-DCA,Business,2022-12-31,Active,3/2/17,Tobacco Retail Dealer,NEW WAY NATURAL MARKET AND DELI CORP,NaN,390,TOMPKINS AVE,...,303.0,36.0,3338716.0,3.018340e+09,BK75,267.0,NaN,-73.944038,40.683912,"(40.68391213302259, -73.94403775899217)"
14511,2059587-2-DCA,Business,2022-12-31,Inactive,10/19/17,Tobacco Retail Dealer,GATE FINEST DELI CORP,NaN,318,TOMPKINS AVE,...,303.0,36.0,3051170.0,3.018140e+09,BK75,265.0,NaN,-73.944612,40.686794,"(40.68679442152985, -73.94461225818598)"
11678,2099856-2-DCA,Business,2022-12-31,Active,7/2/21,Tobacco Retail Dealer,FULTON DELI AND SMOKE SHOP CORP,NaN,1403,FULTON ST,...,303.0,36.0,3053471.0,3.018540e+09,NaN,NaN,NaN,-73.945068,40.680155,"(40.68015503534684, -73.9450684449953)"
3351,1221510-DCA,Business,2022-12-31,Inactive,3/21/06,Tobacco Retail Dealer,DEAN DELI GROCERY CORP.,NaN,1050,DEAN ST,...,308.0,35.0,3030246.0,3.012110e+09,BK61,221.0,NaN,-73.955057,40.677486,"(40.67748596060282, -73.95505714467012)"
10353,2099566-2-DCA,Business,2022-12-31,Active,6/21/21,Tobacco Retail Dealer,JAYRAN DELI GROCERY INC,NaN,1050,DEAN ST,...,308.0,35.0,3030246.0,3.012110e+09,NaN,NaN,NaN,-73.955057,40.677486,"(40.67748596060282, -73.95505714467012)"
7804,2098906-2-DCA,Business,2022-12-31,Active,5/25/21,Tobacco Retail Dealer,613 FRESH DELI AND GROCERY CORP,NaN,613,NOSTRAND AVE,...,308.0,36.0,3337844.0,3.012130e+09,NaN,NaN,NaN,-73.949892,40.676213,"(40.67621299633303, -73.94989179930965)"
13881,2083558-2-DCA,Business,2022-12-31,Active,3/22/19,Tobacco Retail Dealer,TONY DELI GROCERY 1 CORP.,NaN,1478,BEDFORD AVE,...,308.0,35.0,3031803.0,3.012450e+09,BK61,219.0,NaN,-73.954375,40.672625,"(40.6726246953942, -73.9543754757304)"
13846,2059582-2-DCA,Business,2022-12-31,Active,10/19/17,Tobacco Retail Dealer,GREENLAND MINI MARKET DELI INC,NaN,784,MARCY AVE,...,303.0,36.0,3322225.0,3.018080e+09,BK75,251.0,NaN,-73.947536,40.686922,"(40.68692205131839, -73.94753641166716)"
13861,2090468-2-DCA,Business,2022-12-31,Active,9/12/19,Tobacco Retail Dealer,367 FAMOUS DELI CORP,NaN,753,MARCY AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947759,40.688152,"(40.68815181005619, -73.94775900442599)"
13816,1257496-DCA,Business,2022-12-31,Active,6/1/07,Tobacco Retail Dealer,"ALREZAKI, AHMED A & ALZOOKARI, MUGALLI S",CROWN HEIGHTS DELI & GROCERY,117,ROGERS AVE,...,308.0,36.0,3031491.0,3.012400e+09,BK61,31701.0,NaN,-73.952937,40.673437,"(40.67343656942923, -73.95293651891095)"
2582,2011041-1-DCA,Business,2021-12-31,Active,7/22/14,Tobacco Retail Dealer,PAPA DELI & GROCERY CORP.,NaN,849,MARCY AVE,...,303.0,36.0,3322392.0,3.018290e+09,BK75,267.0,NaN,-73.946983,40.684270,"(40.6842703482155, -73.94698323520508)"
2741,2046032-1-DCA,Business,2021-12-31,Active,11/30/16,Tobacco Retail Dealer,NOSTRAND FINEST DELI INC,NaN,792,NOSTRAND AVE,...,308.0,35.0,3032243.0,3.012540e+09,BK61,31702.0,NaN,-73.950357,40.671506,"(40.67150590758534, -73.95035676440332)"
3732,2082032-1-DCA,Business,2021-12-31,Active,2/6/19,Tobacco Retail Dealer,S GOURMET DELI CORP,NaN,1558,FULTON ST,...,303.0,36.0,3338777.0,3.018640e+09,BK61,271.0,NaN,-73.938720,40.679795,"(40.67979500866878, -73.93871970236303)"
13228,2095489-1-DCA,Business,2021-12-31,Inactive,3/23/20,Tobacco Retail Dealer,"GREEN PARK GOURMET DELI, INC",NaN,264,TOMPKINS AVE,...,303.0,36.0,3050449.0,3.017990e+09,NaN,NaN,NaN,-73.945047,40.688993,"(40.68899319146262, -73.94504674049102)"
173,2076764-1-DCA,Business,2021-12-31,Active,8/7/18,Tobacco Retail Dealer,JHOAN & BROTHER DELI GROCERY CORP,NaN,759,DEKALB AVE,...,303.0,36.0,3049501.0,3.017750e+09,BK75,261.0,NaN,-73.946223,40.691977,"(40.691977312521956, -73.94622344915649)"
7383,2080593-1-DCA,Business,2021-12-31,Inactive,12/10/18,Tobacco Retail Dealer,PRINCESS DELI AND SMOKE SHOP CORP,NaN,1318,FULTON ST,...,303.0,36.0,3053757.0,3.018610e+09,BK61,247.0,NaN,-73.948180,40.680307,"(40.68030744119197, -73.94817976904972)"
14326,2066589-1-DCA,Business,2021-12-31,Inactive,2/23/18,Tobacco Retail Dealer,BRKLYN DELI AND GRILL CORP,BROOKLYN GOURMET MARKET,1181,BEDFORD AVE,...,303.0,36.0,3329696.0,3.018270e+09,BK75,245.0,NaN,-73.953835,40.683024,"(40.6830244295472, -73.95383474133375)"
2230,1359661-DCA,Business,2021-12-31,Active,6/21/10,Tobacco Retail Dealer,SUPER EXPRESS DELI & GROCERY CORP. I,NaN,1205,BEDFORD AVE,...,303.0,36.0,3322555.0,3.018320e+09,BK75,245.0,NaN,-73.953673,40.682228,"(40.68222838047677, -73.9536730453112)"
11124,2043166-1-DCA,Business,2021-12-31,Inactive,9/1/16,Tobacco Retail Dealer,1403 FULTON GOURMET DELI CORP,NaN,1403,FULTON ST,...,303.0,36.0,3053471.0,3.018540e+09,BK75,269.0,NaN,-73.945068,40.680155,"(40.68015503534684, -73.9450684449953)"
14215,2097367-1-DCA,Business,2021-12-31,Active,12/30/20,Tobacco Retail Dealer,ALSQER DELI & GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,NaN,NaN,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
2721,2068454-1-DCA,Business,2021-11-30,Active,3/28/18,Electronic Cigarette Dealer,MY BUS STOP DELI AND GROCERY CORP,NaN,546A,NOSTRAND AVE,...,303.0,36.0,3053724.0,3.018600e+09,BK61,247.0,NaN,-73.949583,40.679984,"(40.67998418109907, -73.94958250923996)"
8348,2051985-2-DCA,Business,2020-12-31,Inactive,4/26/17,Tobacco Retail Dealer,BEDFORD DELI AND GROCERY CORP,NaN,1478,BEDFORD AVE,...,308.0,35.0,3031803.0,3.012450e+09,BK61,219.0,NaN,-73.954375,40.672625,"(40.6726246953942, -73.9543754757304)"
710,1211022-DCA,Business,2020-12-31,Inactive,9/26/05,Tobacco Retail Dealer,"KAID, AHMED M",TOMPKINS DELI GROCERY,264,TOMPKINS AVE,...,303.0,36.0,3050449.0,3.017990e+09,BK75,263.0,NaN,-73.945047,40.688993,"(40.68899319146262, -73.94504674049102)"
6333,1306164-DCA,Business,2020-12-31,Inactive,12/16/08,Tobacco Retail Dealer,G LINE DELI GROCERY INC,NaN,292,NOSTRAND AVE,...,303.0,36.0,3049897.0,3.017880e+09,BK75,243.0,NaN,-73.951465,40.689817,"(40.68981676356796, -73.95146456703722)"
540,2093313-2-DCA,Business,2020-12-31,Inactive,1/2/20,Tobacco Retail Dealer,NA ROCK DELI CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,NaN,NaN,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
1825,2053539-2-DCA,Business,2020-12-31,Inactive,5/25/17,Tobacco Retail Dealer,B DELI GROCERY CORP,NaN,684,NOSTRAND AVE,...,308.0,36.0,3030970.0,3.012260e+09,BK61,31701.0,NaN,-73.950026,40.675025,"(40.67502456711211, -73.9500260809846)"
240,2052492-2-DCA,Business,2020-12-31,Inactive,5/4/17,Tobacco Retail Dealer,KRISTAL DELI GROCERY NY CORP,NaN,1565,FULTON ST,...,303.0,36.0,3053680.0,3.018580e+09,BK35,273.0,NaN,-73.938835,40.679817,"(40.679817028236805, -73.93883505369406)"
2817,2066793-1-DCA,Business,2019-12-31,Inactive,2/23/18,Tobacco Retail Dealer,BARCELONA DELI AND GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,BK75,245.0,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
8005,2066670-1-DCA,Business,2019-12-31,Inactive,2/23/18,Tobacco Retail Dealer,MERIT DELI AND SMOKE SHOP CORP,NaN,1318,FULTON ST,...,303.0,36.0,3053757.0,3.018610e+09,BK61,247.0,NaN,-73.948180,40.680307,"(40.68030744119197, -73.94817976904972)"
10296,2039601-1-DCA,Business,2019-12-31,Inactive,6/28/16,Tobacco Retail Dealer,FAMILY FOOD & DELI CORP,NaN,1053,BEDFORD AVE,...,303.0,36.0,3050325.0,3.017970e+09,BK75,243.0,NaN,-73.954787,40.687812,"(40.68781168955238, -73.95478696214188)"
8830,2011197-1-DCA,Business,2019-12-31,Inactive,7/25/14,Tobacco Retail Dealer,J M DELI GROCERY CORP I,NaN,1369,FULTON ST,...,303.0,36.0,3053280.0,3.018500e+09,BK75,249.0,NaN,-73.946456,40.680233,"(40.68023254327992, -73.94645645386848)"
309,2066345-1-DCA,Business,2019-12-31,Inactive,2/20/18,Tobacco Retail Dealer,DEAN DELI CORPORATION,NaN,628,NOSTRAND AVE,...,308.0,36.0,3030004.0,3.012060e+09,BK61,315.0,NaN,-73.949844,40.676990,"(40.676989746923105, -73.94984434799078)"
12276,2066039-1-DCA,Business,2019-12-31,Inactive,2/13/18,Tobacco Retail Dealer,753 FAMOUS DELI CORP,NaN,753,MARCY AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947759,40.688152,"(40.68815181005619, -73.94775900442599)"
12092,1453015-DCA,Business,2019-12-31,Inactive,12/31/12,Tobacco Retail Dealer,RAJIH DELI AND GROCERY INC,NaN,689A,NOSTRAND AVE,...,308.0,36.0,3341625.0,3.012340e+09,BK61,31701.0,NaN,-73.950124,40.673713,"(40.6737126070741, -73.95012439987542)"
340,2006228-1383-DCA,Business,2019-12-31,Inactive,4/14/14,Tobacco Retail Dealer,367 deli and grocery inc,NaN,367,LEXINGTON AVE,...,303.0,36.0,3050418.0,3.017990e+09,BK75,263.0,NaN,-73.947485,40.688080,"(40.68808032130511, -73.94748501902926)"
9378,2053835-2-DCA,Business,2018-12-31,Inactive,6/2/17,Tobacco Retail Dealer,K GOURMET DELI CORP,NaN,1558,FULTON ST,...,303.0,36.0,3338777.0,3.018640e+09,BK61,271.0,NaN,-73.938720,40.679795,"(40.67979500866878, -73.93871970236303)"
6968,2028147-2-DCA,Business,2018-12-31,Inactive,9/8/15,Tobacco Retail Dealer,J.V. DELI & GROCERY CORP.,NaN,925A,MARCY AVE,...,303.0,36.0,3331201.0,3.018510e+09,BK75,269.0,NaN,-73.946416,40.681391,"(40.681390818778496, -73.94641586396304)"
11482,1400210-DCA,Business,2018-12-31,Inactive,7/15/11,Tobacco Retail Dealer,NBA DELI AND GROCERY CORP,NaN,496,NOSTRAND AVE,...,303.0,36.0,3052610.0,3.018370e+09,BK75,245.0,NaN,-73.949905,40.681969,"(40.68196879328704, -73.9499055017563)"
12618,2058481-2-DCA,Business,2018-12-31,Inactive,9/20/17,Tobacco Retail Dealer,SAKAFE DELI GROCERY CORP,NaN,813,MARCY AVE,...,303.0,36.0,3051455.0,3.018190e+09,BK75,265.0,NaN,-73.947278,40.685736,"(40.685736191780094, -73.94727773562067)"
7741,2049021-2-DCA,Business,2018-12-31,Inactive,3/2/17,Tobacco Retail Dealer,GOURMET 438 DELI INC,NaN,438,NOSTRAND AVE,...,303.0,36.0,3338697.0,3.018220e+09,BK75,245.0,NaN,-73.950333,40.684113,"(40.684112646005126, -73.95033295685029)"
10234,2059337-2-DCA,Business,2018-12-31,Inactive,10/13/17,Tobacco Retail Dealer,KARTER'S GROCERY & DELI INC,NaN,350,TOMPKINS AVE,...,303.0,36.0,3051462.0,3.018190e+09,BK75,265.0,NaN,-73.944375,40.685620,"(40.68561954494297, -73.94437525951625)"
7640,2052741-2-DCA,Business,2018-12-31,Inactive,5/10/17,Tobacco Retail Dealer,FANTASTIC DELI GROCERY CORP,NaN,925A,MARCY AVE,...,303.0,36.0,3331201.0,3.018510e+09,BK75,269.0,NaN,-73.946416,40.681391,"(40.681390818778496, -73.94641586396304)"
9204,1248248-DCA,Business,2018-12-31,Inactive,2/13/07,Tobacco Retail Dealer,SEVEN & ONE DELI GROCERY FULTON STREET CORP,NaN,1521,FULTON ST,...,303.0,36.0,3053619.0,3.018570e+09,BK75,269.0,NaN,-73.940457,40.679906,"(40.679905711966825, -73.9404573871347)"
12979,2048789-2-DCA,Business,2018-12-31,Inactive,2/28/17,Tobacco Retail Dealer,GATES GOURMET DELI AND SUPER MARKET CORP,NaN,349,NOSTRAND AVE,...,303.0,36.0,3000000.0,3.018088e+09,BK75,251.0,NaN,-73.950746,40.686311,"(40.686311385808224, -73.95074597604938)"
13309,2051395-2-DCA,Business,2018-12-31,Inactive,4/18/17,Tobacco Retail Dealer,SALMAN DELI CORP,NaN,1274,FULTON ST,...,303.0,36.0,3053721.0,3.018600e+09,BK61,247.0,NaN,-73.949899,40.680402,"(40.680401525131494, -73.94989946827623)"

Export to CSV

In [99]:
df_11216.to_csv('../output/DCA_License_11216.csv', index = False)